export type Language = 'en' | 'th';

const en = {
  generate: 'Generate', scan: 'Scan', generateTitle: 'Generate QR Code', reset: 'Reset', content: 'Content', colors: 'Colors', logo: 'Logo', customizeDesign: 'Customize Design', appearance: 'Appearance', logoReliability: 'Logo & Reliability', website: 'Website', text: 'Text', wifi: 'Wi-Fi', email: 'Email', phone: 'Phone', sms: 'SMS', automaticCorrection: 'Automatic correction', waitingValid: 'Waiting for valid content', lowContrast: 'Low color contrast may make this QR code hard to scan.', safeSettings: 'Use safe settings', language: 'Language', theme: 'Toggle color theme', characters: 'characters', approachingLimit: 'Approaching the text limit', yourText: 'Your text', textPlaceholder: 'Type or paste text', preview: 'Preview', ready: 'Ready', generating: 'Generating', waiting: 'Waiting', download: 'Download', imageSize: 'Image size', fileFormat: 'File format', generatedLocally: 'Generated locally', scanTitle: 'Scan QR Code', scanSubtitle: 'Scan from an image or camera.', scanImage: 'Scan image', camera: 'Camera', dragBrowse: 'Drag & Drop or Browse', browseFiles: 'Browse files', pasteImage: 'Paste image', startCamera: 'Start camera', stopCamera: 'Stop camera', scannedResult: 'Scanned Result', waitingImage: 'Waiting for image', waitingCamera: 'Waiting for camera', scanning: 'Scanning', success: 'Success', noQr: 'No QR code found', resultPlaceholder: 'Your decoded QR content will appear here.', copyResult: 'Copy result', copied: 'Copied', openLink: 'Open link', scanAgain: 'Scan again', cameraPreview: 'Camera preview', cameraLabel: 'Camera', pngJpgWebp: 'PNG, JPG, WEBP', addLogo: 'Add logo', replace: 'Replace', upload: 'Upload', removeLogo: 'Remove logo', foreground: 'Foreground', background: 'Background', dotStyle: 'Dot style', cornerSquares: 'Corner squares', cornerDots: 'Corner dots', rounded: 'Rounded', square: 'Square', circle: 'Circle', security: 'Security', noPassword: 'No password', hiddenNetwork: 'Hidden network', networkName: 'Network name (SSID)', password: 'Password', emailAddress: 'Email address', subject: 'Subject (optional)', message: 'Message (optional)', phoneNumber: 'Phone number', websiteUrl: 'Website URL', logoLimit: 'Logo size is limited to 22% and higher correction is selected when capacity allows.', colorWarning: 'Low color contrast may make this QR code hard to scan.',
} as const;
const th: Record<keyof typeof en, string> = {
  generate: 'สร้าง', scan: 'สแกน', generateTitle: 'สร้างคิวอาร์โค้ด', reset: 'รีเซ็ต', content: 'เนื้อหา', colors: 'สี', logo: 'โลโก้', customizeDesign: 'ปรับแต่งรูปแบบ', appearance: 'รูปแบบ', logoReliability: 'โลโก้และความน่าเชื่อถือ', website: 'เว็บไซต์', text: 'ข้อความ', wifi: 'Wi‑Fi', email: 'อีเมล', phone: 'โทรศัพท์', sms: 'SMS', automaticCorrection: 'การแก้ไขข้อผิดพลาดอัตโนมัติ', waitingValid: 'รอข้อมูลที่ถูกต้อง', lowContrast: 'สีมีความต่างต่ำ อาจทำให้สแกนคิวอาร์โค้ดได้ยาก', safeSettings: 'ใช้การตั้งค่าที่ปลอดภัย', language: 'ภาษา', theme: 'สลับโหมดสี', characters: 'ตัวอักษร', approachingLimit: 'ใกล้ถึงขีดจำกัดข้อความ', yourText: 'ข้อความของคุณ', textPlaceholder: 'พิมพ์หรือวางข้อความ', preview: 'ตัวอย่าง', ready: 'พร้อม', generating: 'กำลังสร้าง', waiting: 'รอ', download: 'ดาวน์โหลด', imageSize: 'ขนาดภาพ', fileFormat: 'รูปแบบไฟล์', generatedLocally: 'สร้างบนอุปกรณ์นี้', scanTitle: 'สแกนคิวอาร์โค้ด', scanSubtitle: 'สแกนจากรูปภาพหรือกล้อง', scanImage: 'สแกนรูปภาพ', camera: 'กล้อง', dragBrowse: 'ลากและวาง หรือเลือกไฟล์', browseFiles: 'เลือกไฟล์', pasteImage: 'วางรูปภาพ', startCamera: 'เปิดกล้อง', stopCamera: 'หยุดกล้อง', scannedResult: 'ผลการสแกน', waitingImage: 'รอรูปภาพ', waitingCamera: 'รอกล้อง', scanning: 'กำลังสแกน', success: 'สำเร็จ', noQr: 'ไม่พบคิวอาร์โค้ด', resultPlaceholder: 'เนื้อหาจากคิวอาร์โค้ดจะแสดงที่นี่', copyResult: 'คัดลอกผลลัพธ์', copied: 'คัดลอกแล้ว', openLink: 'เปิดลิงก์', scanAgain: 'สแกนอีกครั้ง', cameraPreview: 'ภาพจากกล้อง', cameraLabel: 'กล้อง', pngJpgWebp: 'PNG, JPG, WEBP', addLogo: 'เพิ่มโลโก้', replace: 'แทนที่', upload: 'อัปโหลด', removeLogo: 'ลบโลโก้', foreground: 'สีลาย', background: 'สีพื้นหลัง', dotStyle: 'รูปแบบจุด', cornerSquares: 'มุมหลัก', cornerDots: 'จุดมุม', rounded: 'โค้งมน', square: 'สี่เหลี่ยม', circle: 'วงกลม', security: 'ความปลอดภัย', noPassword: 'ไม่ใช้รหัสผ่าน', hiddenNetwork: 'เครือข่ายซ่อน', networkName: 'ชื่อเครือข่าย (SSID)', password: 'รหัสผ่าน', emailAddress: 'ที่อยู่อีเมล', subject: 'หัวข้อ (ไม่บังคับ)', message: 'ข้อความ (ไม่บังคับ)', phoneNumber: 'หมายเลขโทรศัพท์', websiteUrl: 'URL เว็บไซต์', logoLimit: 'จำกัดขนาดโลโก้ที่ 22% และจะเลือกระดับแก้ไขข้อผิดพลาดสูงเมื่อรองรับ', colorWarning: 'สีมีความต่างต่ำ อาจทำให้สแกนคิวอาร์โค้ดได้ยาก',
};
export type TranslationKey = keyof typeof en;
export const t = (language: Language, key: TranslationKey) => (language === 'th' ? th : en)[key];
export function translateValidationError(language: Language, error?: string) {
  if (!error || language === 'en') return error;
  if (error.includes('too dense')) return 'ข้อมูลนี้ทำให้คิวอาร์โค้ดหนาแน่นเกินไปสำหรับการสแกนที่เชื่อถือได้ โปรดย่อข้อมูลให้สั้นลง';
  if (error.includes('exceeds QR')) return 'ข้อมูลนี้เกินความจุของคิวอาร์โค้ด โปรดย่อข้อมูลให้สั้นลง';
  if (error.includes('website URL')) return 'กรุณากรอก URL เว็บไซต์';
  if (error.includes('http://')) return 'กรุณากรอก URL ที่ขึ้นต้นด้วย http:// หรือ https://';
  if (error.includes('text')) return 'กรุณากรอกข้อความที่ต้องการแชร์';
  if (error.includes('network')) return 'กรุณากรอกชื่อเครือข่าย';
  if (error.includes('password')) return 'กรุณากรอกรหัสผ่าน Wi‑Fi';
  if (error.includes('email')) return 'กรุณากรอกอีเมลที่ถูกต้อง';
  if (error.includes('phone')) return 'กรุณากรอกหมายเลขโทรศัพท์ที่ถูกต้อง';
  return error;
}
